services:
  wedding-race-backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  wedding-race-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - wedding-race-backend
    networks:
      - app-network
    env_file:
      - ./frontend/.env.local

networks:
  app-network: